apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepools
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/salanisor/eks-learning
    targetRevision: main
    path: gitops/karpenter/nodepools
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
