apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: test-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: test-app-secrets
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks-learning/dev/test-app/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: eks-learning/dev/test-app/db-credentials
        property: password
