apiVersion: v1
kind: Namespace
metadata:
  name: test-app
  labels:
    team: test-app
    environment: dev
    managed-by: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-app-rolebinding
  namespace: test-app
subjects:
  - kind: ServiceAccount
    name: test-app-sa
    namespace: test-app
roleRef:
  kind: Role
  name: test-app-role
  apiGroup: rbac.authorization.k8s.io
