apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments
  namespace: argocd
spec:
  project: dev-tenants
  source:
    repoURL: https://github.com/salanisor/eks-learning
    targetRevision: main
    path: gitops/tenants/dev/payments
  destination:
    server: https://kubernetes.default.svc
    namespace: payments
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data
