apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: payments
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payments-secrets
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks-learning/dev/payments/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: eks-learning/dev/payments/db-credentials
        property: password
